import Foundation

/// Writes BRAIN-INDEX.md: the one-line-per-note catalogue every agent reads first.
/// Rebuilt wholesale on every launch, save, and capture, so it can never drift from disk.
/// ponytail: full rebuild each time; go incremental if the vault ever passes ~20k notes.
enum BrainIndex {
    static let dateFormat: DateFormatter = {
        let f = DateFormatter()
        f.dateFormat = "yyyy-MM-dd HH:mm"
        return f
    }()
    static let dayFormat: DateFormatter = {
        let f = DateFormatter()
        f.dateFormat = "yyyy-MM-dd"
        return f
    }()

    @discardableResult
    static func write(notes: [Note], to file: URL) -> Bool {
        var out = "# Brain Index\n\n"
        out += "> Generated by CodexBrain — do not edit by hand. Check this file FIRST, open note files second.\n"
        out += "> Rebuild: `codexbrain reindex` · Ask: `codexbrain ask \"question\"`\n\n"
        out += "Updated \(dateFormat.string(from: Date())) · \(notes.count) notes\n"

        let byRoot = Dictionary(grouping: notes, by: \.rootName)
        for rootName in byRoot.keys.sorted() {
            out += "\n## \(rootName)\n\n"
            let sorted = byRoot[rootName]!.sorted {
                ($0.folder, $0.title.lowercased()) < ($1.folder, $1.title.lowercased())
            }
            for note in sorted {
                let desc = note.description.isEmpty ? "" : " — \(note.description)"
                let place = note.folder.isEmpty ? "root" : note.folder
                out += "- [\(note.title)](\(note.url.path))\(desc) (\(place) · \(dayFormat.string(from: note.modified)))\n"
            }
        }
        return (try? out.write(to: file, atomically: true, encoding: .utf8)) != nil
    }
}
